=== valsavva/DynaCat/Documentation/schema0.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Level" nillable="true" type="Level" />
  <xs:complexType name="Level">
    <xs:complexContent mixed="false">
      <xs:extension base="Screen" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Screen">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement">
        <xs:attribute name="Name" type="xs:string" />
        <xs:attribute name="File" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="XElement">
    <xs:complexContent mixed="false">
      <xs:extension base="XObject">
        <xs:attribute name="Opacity" type="xs:float" use="required" />
        <xs:attribute name="Rotation" type="xs:float" use="required" />
        <xs:attribute name="Bounds" type="xs:string" />
        <xs:attribute name="BackColor" type="xs:string" />
        <xs:attribute name="Origin" type="xs:string" />
        <xs:attribute name="RotationCenter" type="xs:string" />
        <xs:attribute name="Scale" type="xs:string" />
        <xs:attribute name="Location" type="xs:string" />
        <xs:attribute name="Center" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="XObject" abstract="true">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="1" name="Iterator" type="Iterator" />
        <xs:element minOccurs="0" maxOccurs="1" name="Resources" type="Resources" />
        <xs:element minOccurs="0" maxOccurs="1" name="Dashboard" type="Dashboard" />
        <xs:element minOccurs="0" maxOccurs="1" name="TapArea" type="TapArea" />
        <xs:element minOccurs="0" maxOccurs="1" name="Include" type="Include" />
        <xs:element minOccurs="0" maxOccurs="1" name="Music" type="Music" />
        <xs:element minOccurs="0" maxOccurs="1" name="Sound" type="Sound" />
        <xs:element minOccurs="0" maxOccurs="1" name="Viewport" type="Viewport" />
        <xs:element minOccurs="0" maxOccurs="1" name="LevelSettings" type="LevelSettings" />
        <xs:element minOccurs="0" maxOccurs="1" name="Layer" type="Layer" />
        <xs:element minOccurs="0" maxOccurs="1" name="IntersectionTrigger" type="IntersectionTrigger" />
        <xs:element minOccurs="0" maxOccurs="1" name="DistanceTrigger" type="DistanceTrigger" />
        <xs:element minOccurs="0" maxOccurs="1" name="BoolTrigger" type="BoolTrigger" />
        <xs:element minOccurs="0" maxOccurs="1" name="NumTrigger" type="NumTrigger" />
        <xs:element minOccurs="0" maxOccurs="1" name="Class" type="Class" />
        <xs:element minOccurs="0" maxOccurs="1" name="Tower" type="Tower" />
        <xs:element minOccurs="0" maxOccurs="1" name="Hero" type="Hero" />
        <xs:element minOccurs="0" maxOccurs="1" name="Enemy" type="Enemy" />
        <xs:element minOccurs="0" maxOccurs="1" name="Food" type="Food" />
        <xs:element minOccurs="0" maxOccurs="1" name="Explosion" type="Explosion" />
        <xs:element minOccurs="0" maxOccurs="1" name="Text" type="Text" />
        <xs:element minOccurs="0" maxOccurs="1" name="SequenceSet" type="SequenceSet" />
        <xs:element minOccurs="0" maxOccurs="1" name="RandomSet" type="RandomSet" />
        <xs:element minOccurs="0" maxOccurs="1" name="ParallelSet" type="ParallelSet" />
        <xs:element minOccurs="0" maxOccurs="1" name="Do" type="Do" />
        <xs:element minOccurs="0" maxOccurs="1" name="Block" type="Block" />
        <xs:element minOccurs="0" maxOccurs="1" name="NumAnimation" type="NumAnimation" />
        <xs:element minOccurs="0" maxOccurs="1" name="KeyFrame" type="KeyFrame" />
        <xs:element minOccurs="0" maxOccurs="1" name="Group" type="Group" />
        <xs:element minOccurs="0" maxOccurs="1" name="Image" type="Image" />
        <xs:element minOccurs="0" maxOccurs="1" name="Delay" type="Delay" />
        <xs:element minOccurs="0" maxOccurs="1" name="Sprite" type="Sprite" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="Id" type="xs:string" />
    <xs:attribute name="Class" type="xs:string" />
    <xs:attribute name="ClassParams" type="xs:string" />
    <xs:attribute name="Enabled" type="xs:boolean" use="required" />
  </xs:complexType>
  <xs:complexType name="Iterator">
    <xs:complexContent mixed="false">
      <xs:extension base="XRunnableBase">
        <xs:attribute name="TypeFilter" type="xs:string" />
        <xs:attribute name="ObjectIds" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="XRunnableBase" abstract="true">
    <xs:complexContent mixed="false">
      <xs:extension base="XObject">
        <xs:attribute name="InProgress" type="xs:boolean" use="required" />
        <xs:attribute name="RepeatCount" type="xs:float" use="required" />
        <xs:attribute name="RepeatTime" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="XAnimationBase" abstract="true">
    <xs:complexContent mixed="false">
      <xs:extension base="XRunnableBase">
        <xs:attribute name="Autoreverse" type="xs:boolean" use="required" />
        <xs:attribute name="Fill" type="XAnimationFillBehavior" use="required" />
        <xs:attribute name="Duration" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:simpleType name="XAnimationFillBehavior">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Hold" />
      <xs:enumeration value="Reset" />
      <xs:enumeration value="End" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="NumAnimation">
    <xs:complexContent mixed="false">
      <xs:extension base="XAnimationBase">
        <xs:attribute name="Target" type="xs:string" />
        <xs:attribute name="From" type="xs:string" />
        <xs:attribute name="To" type="xs:string" />
        <xs:attribute name="IsDelta" type="xs:boolean" use="required" />
        <xs:attribute name="Smoothing" type="CurveTangent" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:simpleType name="CurveTangent">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Flat" />
      <xs:enumeration value="Linear" />
      <xs:enumeration value="Smooth" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="Do">
    <xs:complexContent mixed="false">
      <xs:extension base="XRunnableBase">
        <xs:attribute name="Action" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="XSetBase" abstract="true">
    <xs:complexContent mixed="false">
      <xs:extension base="XRunnableBase" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ParallelSet">
    <xs:complexContent mixed="false">
      <xs:extension base="XSetBase" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="RandomSet">
    <xs:complexContent mixed="false">
      <xs:extension base="XSetBase">
        <xs:attribute name="Probabilities" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="SequenceSet">
    <xs:complexContent mixed="false">
      <xs:extension base="XSetBase" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Resources">
    <xs:complexContent mixed="false">
      <xs:extension base="XObject">
        <xs:sequence>
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element minOccurs="0" maxOccurs="1" name="SoundFile" type="SoundFile" />
            <xs:element minOccurs="0" maxOccurs="1" name="Font" type="Font" />
            <xs:element minOccurs="0" maxOccurs="1" name="Texture" type="Texture" />
            <xs:element minOccurs="0" maxOccurs="1" name="MusicFile" type="MusicFile" />
          </xs:choice>
        </xs:sequence>
        <xs:attribute name="RootFolder" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="SoundFile">
    <xs:complexContent mixed="false">
      <xs:extension base="XResource" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="XResource" abstract="true">
    <xs:complexContent mixed="false">
      <xs:extension base="XObject">
        <xs:attribute name="Source" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="MusicFile">
    <xs:complexContent mixed="false">
      <xs:extension base="XResource" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Texture">
    <xs:complexContent mixed="false">
      <xs:extension base="XResource" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Font">
    <xs:complexContent mixed="false">
      <xs:extension base="XResource" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Dashboard">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="TapArea">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement">
        <xs:attribute name="Event" type="xs:string" />
        <xs:attribute name="Action" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Include">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement">
        <xs:attribute name="File" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Music">
    <xs:complexContent mixed="false">
      <xs:extension base="XObject">
        <xs:sequence>
          <xs:element minOccurs="1" maxOccurs="1" name="InProgress" type="xs:boolean" />
        </xs:sequence>
        <xs:attribute name="FileId" type="xs:string" />
        <xs:attribute name="Volume" type="xs:float" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Sound">
    <xs:complexContent mixed="false">
      <xs:extension base="XObject">
        <xs:sequence>
          <xs:element minOccurs="1" maxOccurs="1" name="InProgress" type="xs:boolean" />
        </xs:sequence>
        <xs:attribute name="FileId" type="xs:string" />
        <xs:attribute name="Pitch" type="xs:float" use="required" />
        <xs:attribute name="Pan" type="xs:float" use="required" />
        <xs:attribute name="IsLooped" type="xs:boolean" use="required" />
        <xs:attribute name="Volume" type="xs:float" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Viewport">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="LevelSettings">
    <xs:complexContent mixed="false">
      <xs:extension base="XObject">
        <xs:attribute name="Difficulty" type="xs:int" use="required" />
        <xs:attribute name="BombCount" type="xs:int" use="required" />
        <xs:attribute name="HeroHealth" type="xs:float" use="required" />
        <xs:attribute name="ExplosionClass" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Layer">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="IntersectionTrigger">
    <xs:complexContent mixed="false">
      <xs:extension base="XNumTriggerBase">
        <xs:attribute name="ObjectId1" type="xs:string" />
        <xs:attribute name="ObjectId2" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="XNumTriggerBase" abstract="true">
    <xs:complexContent mixed="false">
      <xs:extension base="XTriggerBase">
        <xs:attribute name="Value" type="xs:string" />
        <xs:attribute name="Compare" type="XValueComparison" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="XTriggerBase" abstract="true">
    <xs:complexContent mixed="false">
      <xs:extension base="XObject">
        <xs:attribute name="EnterAction" type="xs:string" />
        <xs:attribute name="ExitAction" type="xs:string" />
        <xs:attribute name="Action" type="xs:string" />
        <xs:attribute name="Group" type="xs:string" />
        <xs:attribute name="StayTriggered" type="xs:boolean" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="BoolTrigger">
    <xs:complexContent mixed="false">
      <xs:extension base="XTriggerBase">
        <xs:attribute name="Condition" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:simpleType name="XValueComparison">
    <xs:restriction base="xs:string">
      <xs:enumeration value="E" />
      <xs:enumeration value="G" />
      <xs:enumeration value="GE" />
      <xs:enumeration value="L" />
      <xs:enumeration value="LE" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="NumTrigger">
    <xs:complexContent mixed="false">
      <xs:extension base="XNumTriggerBase">
        <xs:attribute name="Property" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DistanceTrigger">
    <xs:complexContent mixed="false">
      <xs:extension base="XNumTriggerBase">
        <xs:attribute name="ObjectId1" type="xs:string" />
        <xs:attribute name="ObjectId2" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Class">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Tower">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement">
        <xs:attribute name="SignalSpeed" type="xs:double" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Hero">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement">
        <xs:attribute name="Speed" type="xs:float" use="required" />
        <xs:attribute name="Direction" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Enemy">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement">
        <xs:attribute name="Damage" type="xs:float" use="required" />
        <xs:attribute name="IsExploding" type="xs:boolean" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Food">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement">
        <xs:attribute name="Points" type="xs:float" use="required" />
        <xs:attribute name="IsExploding" type="xs:boolean" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Explosion">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement">
        <xs:attribute name="Ranges" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Text">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement">
        <xs:attribute name="Text" type="xs:string" />
        <xs:attribute name="FontId" type="xs:string" />
        <xs:attribute name="Color" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Block">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement">
        <xs:attribute name="Edges" type="XEdgeType" use="required" />
        <xs:attribute name="IsExploding" type="xs:boolean" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:simpleType name="XEdgeType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="None" />
      <xs:enumeration value="Bounce" />
      <xs:enumeration value="Stick" />
      <xs:enumeration value="Teleport" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="KeyFrame">
    <xs:complexContent mixed="false">
      <xs:extension base="XObject">
        <xs:attribute name="Value" type="xs:string" />
        <xs:attribute name="Smoothing" type="CurveTangent" use="required" />
        <xs:attribute name="Time" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Group">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement">
        <xs:attribute name="IsExploding" type="xs:boolean" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Image">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement">
        <xs:attribute name="TextureId" type="xs:string" />
        <xs:attribute name="Stretch" type="xs:boolean" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Sprite">
    <xs:complexContent mixed="false">
      <xs:extension base="Image">
        <xs:attribute name="FrameCount" type="xs:int" use="required" />
        <xs:attribute name="CurrentFrame" type="xs:int" use="required" />
        <xs:attribute name="FrameBounds" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Delay">
    <xs:complexContent mixed="false">
      <xs:extension base="XObject">
        <xs:sequence>
          <xs:element minOccurs="1" maxOccurs="1" name="InProgress" type="xs:boolean" />
        </xs:sequence>
        <xs:attribute name="Duration" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
</xs:schema>

=== valsavva/DynaCat/Source/Lunohod/Lunohod/Metadata/ClassTeleportKoleno.xml
<!--<Level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/Lunohod/Documentation/schema0.xsd" >-->
<Include>	

	<Resources RootFolder="Sound">
		<!--<SoundFile Id="sndExplosion" Source="skeletonFX_explosion"/>
		<SoundFile Id="sndBombHiss" Source="bombHiss"/>-->
	</Resources>
   
    <Class Id="clsTeleportKoleno">
        <SequenceSet InProgress="true" RepeatCount="1">
            <Do Action="imgTeleportKoleno.X=@X;imgTeleportKoleno.Y=@Y" />
            <Do Action="imgTeleportKoleno.Enable();hero:bounce" />
            <Do Action="@d=@delay" />
            <Delay Duration="@d" />
            <RandomSet RepeatCount="1">
                <NumAnimation Target="imgTeleportKoleno.Rotation" From="-5" To="5" Duration="0.1" Autoreverse="true" RepeatCount="1" Fill="End"/>
                <NumAnimation Target="imgTeleportKoleno.Rotation" From="5" To="-5" Duration="0.1" Autoreverse="true" RepeatCount="1" Fill="End"/>
                <NumAnimation Target="imgTeleportKoleno.X" From="-2" To="2" IsDelta="true" Duration="0.1" RepeatCount="1" Autoreverse="true" Fill="End"/>
                <NumAnimation Target="imgTeleportKoleno.Y" From="-2" To="2" IsDelta="true" Duration="0.1" RepeatCount="1" Autoreverse="true" Fill="End"/>
            </RandomSet>
            <Do Action="imgTeleportKoleno.Disable()" />
            <Do Action="imgTeleportKoleno.X=-100;imgTeleportKoleno.Y=-100" />
        </SequenceSet>
    </Class>

</Include>

=== valsavva/DynaCat/Source/Lunohod/Lunohod/Metadata/ClassTeleportTube.xml
<!--<Level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/Lunohod/Documentation/schema0.xsd" >-->
<Include>	

	<Resources RootFolder="Sound">
		<!--<SoundFile Id="sndExplosion" Source="skeletonFX_explosion"/>
		<SoundFile Id="sndBombHiss" Source="bombHiss"/>-->
	</Resources>

    <Class Id="clsTeleportTube">
        <SequenceSet InProgress="true" RepeatCount="1">
            <Do Action="hero:+PortCont" />
            <Delay Duration="@delay" />
            <Do Action="imgTeleportTubeHorHero.X=@horX;imgTeleportTubeHorHero.Y=@horY;imgTeleportTubeVertHero.X=@vertX;imgTeleportTubeVertHero.Y=@vertY" />
            <NumAnimation Target="imgTeleportTubeHorHero.X,imgTeleportTubeVertHero.Y" From="0,0" To="@delta,@delta" IsDelta="true" Duration="@duration" RepeatCount="1" Autoreverse="false" Fill="End"/>
            <!--<Do Action="imgTeleportTubeHorHero.Disable();imgTeleportTubeVertHero.Disable()" />-->
            <Do Action="imgTeleportTubeHorHero.X=-7777777;imgTeleportTubeHorHero.Y=-7777777;imgTeleportTubeVertHero.X=-7777777;imgTeleportTubeVertHero.Y=-7777777" />
            <Do Action="hero:-PortCont" />
        </SequenceSet>
    </Class>

</Include>

=== valsavva/DynaCat/Source/Lunohod/Lunohod/Metadata/Lvl_Poezd_v2.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- SVG to XGAME xml converter v1.6.07 -->
<!-- source: D:\Lunohod\Levels\Lvl_Poezd_v2\Lvl_Poezd_v2.svg -->
<Level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/Lunohod/Documentation/schema0.xsd" Name="Lvl_Poezd_v2" Bounds="0, 0, 480, 320">
    <Include File="ClassEnemyRat4.xml" />
    <Include File="ClassFoodFish1.xml" />
    <Include File="ClassTower.xml" />
    <Include File="ClassHero.xml" />
    <Include File="ClassExit.xml" />
    <Resources RootFolder="Textures">
        <Texture Id="txr_backg_demo" Source="backg_demo" />
        <Texture Id="txr_railway2" Source="railway2" />
        <Texture Id="txr_semafor_green" Source="semafor_green" />
    </Resources>
    <Layer Id="background" BackColor="#FFFFFFFF">
        <Image Id="dfltMask1" TextureId="txr_backg_demo" Bounds="0, 0, 480, 320" TraceId="image4744"/>
        <Image Id="dfltMask2" TextureId="txr_railway2" Bounds="0, 0, 480, 320" TraceId="image4733"/>
    </Layer>
    <Layer Id="action" BackColor="#FFFFFFFF">
        <Enemy Id="enm1" Class="clsEnemyRat4" Bounds="401, 55, 22, 23" TraceId="image4799"/>
        <Enemy Id="enm2" Class="clsEnemyRat4" Bounds="45, 115, 22, 23" TraceId="image4801"/>
        <Enemy Id="enm3" Class="clsEnemyRat4" Bounds="189, 250, 22, 23" TraceId="image4803"/>
        <Enemy Id="enm4" Class="clsEnemyRat4" Bounds="401, 176, 22, 23" TraceId="image4606"/>
        <Food Id="fd1" Class="clsFoodFish1" Bounds="159, 34, 30, 15" TraceId="image4761"/>
        <Food Id="fd2" Class="clsFoodFish1" Bounds="193, 30, 30, 15" TraceId="image4763"/>
        <Food Id="fd3" Class="clsFoodFish1" Bounds="273, 33, 30, 15" TraceId="image4765"/>
        <Food Id="fd4" Class="clsFoodFish1" Bounds="357, 33, 30, 15" TraceId="image4767"/>
        <Food Id="fd5" Class="clsFoodFish1" Bounds="376, 85, 30, 15" TraceId="image4769"/>
        <Food Id="fd6" Class="clsFoodFish1" Bounds="365, 94, 30, 15" TraceId="image4771"/>
        <Food Id="fd7" Class="clsFoodFish1" Bounds="240, 90, 30, 15" TraceId="image4773"/>
        <Food Id="fd8" Class="clsFoodFish1" Bounds="214, 100, 30, 15" TraceId="image4775"/>
        <Food Id="fd9" Class="clsFoodFish1" Bounds="57, 83, 30, 15" TraceId="image4777"/>
        <Food Id="fd10" Class="clsFoodFish1" Bounds="65, 158, 30, 15" TraceId="image4779"/>
        <Food Id="fd11" Class="clsFoodFish1" Bounds="86, 147, 30, 15" TraceId="image4781"/>
        <Food Id="fd12" Class="clsFoodFish1" Bounds="114, 160, 30, 15" TraceId="image4783"/>
        <Food Id="fd13" Class="clsFoodFish1" Bounds="325, 153, 30, 15" TraceId="image4785"/>
        <Food Id="fd14" Class="clsFoodFish1" Bounds="342, 219, 30, 15" TraceId="image4787"/>
        <Food Id="fd15" Class="clsFoodFish1" Bounds="288, 217, 30, 15" TraceId="image4789"/>
        <Food Id="fd16" Class="clsFoodFish1" Bounds="231, 206, 30, 15" TraceId="image4791"/>
        <Food Id="fd17" Class="clsFoodFish1" Bounds="358, 269, 30, 15" TraceId="image4793"/>
        <Food Id="fd18" Class="clsFoodFish1" Bounds="376, 263, 30, 15" TraceId="image4795"/>
        <Food Id="fd19" Class="clsFoodFish1" Bounds="333, 267, 30, 15" TraceId="image4797"/>
        <Food Id="fd20" Class="clsFoodFish1" Bounds="332, 277, 30, 15" TraceId="image4663"/>
    </Layer>
    <Layer Id="way" BackColor="#FFFFFFFF">
        <!-- HAND EDIT >>> -->
        <SequenceSet Id="setWay" InProgress="true">
            <Do Action="hero.SetTransaction(false, true, true)" />
            <Delay Duration="3" />
            <NumAnimation From="0" To="398" Target="hero.X" Duration="4.74" IsDelta="true" Autoreverse="false" RepeatCount="1" TraceId="image3336"/>
            <NumAnimation From="0" To="60" Target="hero.Y" Duration="0.71" IsDelta="true" Autoreverse="false" RepeatCount="1" TraceId="image3358"/>
            <NumAnimation From="0" To="-416" Target="hero.X" Duration="4.95" IsDelta="true" Autoreverse="false" RepeatCount="1" TraceId="image4747"/>
            <NumAnimation From="0" To="60" Target="hero.Y" Duration="0.71" IsDelta="true" Autoreverse="false" RepeatCount="1" TraceId="image4749"/>
            <NumAnimation From="0" To="416" Target="hero.X" Duration="4.95" IsDelta="true" Autoreverse="false" RepeatCount="1" TraceId="image4753"/>
            <NumAnimation From="0" To="60" Target="hero.Y" Duration="0.71" IsDelta="true" Autoreverse="false" RepeatCount="1" TraceId="image4755"/>
            <NumAnimation From="0" To="-296" Target="hero.X" Duration="3.52" IsDelta="true" Autoreverse="false" RepeatCount="1" TraceId="image3369"/>
            <NumAnimation From="0" To="60" Target="hero.Y" Duration="0.71" IsDelta="true" Autoreverse="false" RepeatCount="1" TraceId="image4757"/>
            <NumAnimation From="0" To="270" Target="hero.X" Duration="3.21" IsDelta="true" Autoreverse="false" RepeatCount="1" TraceId="image4759"/>
        </SequenceSet>
        <BoolTrigger Condition="hero:Enter" EnterAction="setWay.Stop()" />
        <!-- HAND EDIT <<< -->
    </Layer>
    <Layer Id="actionTHE" BackColor="#FFFFFFFF">
        <Tower Id="tower" Bounds="0, 0, 30, 30" Class="clsTower" TraceId="image3038"/>
        <Hero Id="hero" Class="clsHero" Bounds="26, 23, 33, 24" TraceId="image3015"/>
        <Group Id="exit" Class="clsExit" Bounds="428, 235, 37, 54" TraceId="image3049" />
    </Layer>
    <Layer Id="semafor" BackColor="#FFFFFFFF">
        <Include File="includeSemafor.xml" />
        <Image Id="img_semafor_red" TextureId="txr_semafor_red" Bounds="69, 8, 38, 60" TraceId="image3336-1" />
        <Image Id="img_semafor_green" TextureId="txr_semafor_green" Bounds="69, 8, 38, 60" Enabled="false" TraceId="image3336-1" />
    </Layer>
    <Include File="ClassExplosion.xml" />
    <Include File="Dashboard_Poezd_Series.xml" />
</Level>
<!-- Food=20 Enemy=4 Block=0 DesignImage=2 Animation=0 Teleport Animations=0 FoodPack=0 Oil Barrel=0 dealy sec=0 -->
<!-- -->
<!-- Food Points = 1400 -->
<!-- 1% = 14; 45% = 630; 90% = 1260 -->
<!-- minPointsFood = 70 (5%) -->
<!-- -->
<!-- Enemy Points = 200 -->
<!-- 1% = 2; 45% = 90; 90% = 180 -->
<!-- minPointsEnemy = 50 (25%) -->
<!-- -->
<!-- Food + Enemy Points = 1600 -->
<!-- 1% = 16; 45% = 720; 90% = 1440 -->
<!-- minPointsFood = 70 (4.4%) -->
<!-- minPointsEnemy = 50 (3.1%) -->
