=== valsavva/DynaCat/Documentation/schema0.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Level" nillable="true" type="Level" />
  <xs:complexType name="Level">
    <xs:complexContent mixed="false">
      <xs:extension base="Screen" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Screen">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement">
        <xs:attribute name="Name" type="xs:string" />
        <xs:attribute name="File" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="XElement">
    <xs:complexContent mixed="false">
      <xs:extension base="XObject">
        <xs:attribute name="Opacity" type="xs:float" use="required" />
        <xs:attribute name="Rotation" type="xs:float" use="required" />
        <xs:attribute name="Bounds" type="xs:string" />
        <xs:attribute name="BackColor" type="xs:string" />
        <xs:attribute name="Origin" type="xs:string" />
        <xs:attribute name="RotationCenter" type="xs:string" />
        <xs:attribute name="Scale" type="xs:string" />
        <xs:attribute name="Location" type="xs:string" />
        <xs:attribute name="Center" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="XObject" abstract="true">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="1" name="Iterator" type="Iterator" />
        <xs:element minOccurs="0" maxOccurs="1" name="Resources" type="Resources" />
        <xs:element minOccurs="0" maxOccurs="1" name="Dashboard" type="Dashboard" />
        <xs:element minOccurs="0" maxOccurs="1" name="TapArea" type="TapArea" />
        <xs:element minOccurs="0" maxOccurs="1" name="Include" type="Include" />
        <xs:element minOccurs="0" maxOccurs="1" name="Music" type="Music" />
        <xs:element minOccurs="0" maxOccurs="1" name="Sound" type="Sound" />
        <xs:element minOccurs="0" maxOccurs="1" name="Viewport" type="Viewport" />
        <xs:element minOccurs="0" maxOccurs="1" name="LevelSettings" type="LevelSettings" />
        <xs:element minOccurs="0" maxOccurs="1" name="Layer" type="Layer" />
        <xs:element minOccurs="0" maxOccurs="1" name="IntersectionTrigger" type="IntersectionTrigger" />
        <xs:element minOccurs="0" maxOccurs="1" name="DistanceTrigger" type="DistanceTrigger" />
        <xs:element minOccurs="0" maxOccurs="1" name="BoolTrigger" type="BoolTrigger" />
        <xs:element minOccurs="0" maxOccurs="1" name="NumTrigger" type="NumTrigger" />
        <xs:element minOccurs="0" maxOccurs="1" name="Class" type="Class" />
        <xs:element minOccurs="0" maxOccurs="1" name="Tower" type="Tower" />
        <xs:element minOccurs="0" maxOccurs="1" name="Hero" type="Hero" />
        <xs:element minOccurs="0" maxOccurs="1" name="Enemy" type="Enemy" />
        <xs:element minOccurs="0" maxOccurs="1" name="Food" type="Food" />
        <xs:element minOccurs="0" maxOccurs="1" name="Explosion" type="Explosion" />
        <xs:element minOccurs="0" maxOccurs="1" name="Text" type="Text" />
        <xs:element minOccurs="0" maxOccurs="1" name="SequenceSet" type="SequenceSet" />
        <xs:element minOccurs="0" maxOccurs="1" name="RandomSet" type="RandomSet" />
        <xs:element minOccurs="0" maxOccurs="1" name="ParallelSet" type="ParallelSet" />
        <xs:element minOccurs="0" maxOccurs="1" name="Do" type="Do" />
        <xs:element minOccurs="0" maxOccurs="1" name="Block" type="Block" />
        <xs:element minOccurs="0" maxOccurs="1" name="NumAnimation" type="NumAnimation" />
        <xs:element minOccurs="0" maxOccurs="1" name="KeyFrame" type="KeyFrame" />
        <xs:element minOccurs="0" maxOccurs="1" name="Group" type="Group" />
        <xs:element minOccurs="0" maxOccurs="1" name="Image" type="Image" />
        <xs:element minOccurs="0" maxOccurs="1" name="Delay" type="Delay" />
        <xs:element minOccurs="0" maxOccurs="1" name="Sprite" type="Sprite" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="Id" type="xs:string" />
    <xs:attribute name="Class" type="xs:string" />
    <xs:attribute name="ClassParams" type="xs:string" />
    <xs:attribute name="Enabled" type="xs:boolean" use="required" />
  </xs:complexType>
  <xs:complexType name="Iterator">
    <xs:complexContent mixed="false">
      <xs:extension base="XRunnableBase">
        <xs:attribute name="TypeFilter" type="xs:string" />
        <xs:attribute name="ObjectIds" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="XRunnableBase" abstract="true">
    <xs:complexContent mixed="false">
      <xs:extension base="XObject">
        <xs:attribute name="InProgress" type="xs:boolean" use="required" />
        <xs:attribute name="RepeatCount" type="xs:float" use="required" />
        <xs:attribute name="RepeatTime" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="XAnimationBase" abstract="true">
    <xs:complexContent mixed="false">
      <xs:extension base="XRunnableBase">
        <xs:attribute name="Autoreverse" type="xs:boolean" use="required" />
        <xs:attribute name="Fill" type="XAnimationFillBehavior" use="required" />
        <xs:attribute name="Duration" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:simpleType name="XAnimationFillBehavior">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Hold" />
      <xs:enumeration value="Reset" />
      <xs:enumeration value="End" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="NumAnimation">
    <xs:complexContent mixed="false">
      <xs:extension base="XAnimationBase">
        <xs:attribute name="Target" type="xs:string" />
        <xs:attribute name="From" type="xs:string" />
        <xs:attribute name="To" type="xs:string" />
        <xs:attribute name="IsDelta" type="xs:boolean" use="required" />
        <xs:attribute name="Smoothing" type="CurveTangent" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:simpleType name="CurveTangent">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Flat" />
      <xs:enumeration value="Linear" />
      <xs:enumeration value="Smooth" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="Do">
    <xs:complexContent mixed="false">
      <xs:extension base="XRunnableBase">
        <xs:attribute name="Action" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="XSetBase" abstract="true">
    <xs:complexContent mixed="false">
      <xs:extension base="XRunnableBase" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ParallelSet">
    <xs:complexContent mixed="false">
      <xs:extension base="XSetBase" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="RandomSet">
    <xs:complexContent mixed="false">
      <xs:extension base="XSetBase">
        <xs:attribute name="Probabilities" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="SequenceSet">
    <xs:complexContent mixed="false">
      <xs:extension base="XSetBase" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Resources">
    <xs:complexContent mixed="false">
      <xs:extension base="XObject">
        <xs:sequence>
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element minOccurs="0" maxOccurs="1" name="SoundFile" type="SoundFile" />
            <xs:element minOccurs="0" maxOccurs="1" name="Font" type="Font" />
            <xs:element minOccurs="0" maxOccurs="1" name="Texture" type="Texture" />
            <xs:element minOccurs="0" maxOccurs="1" name="MusicFile" type="MusicFile" />
          </xs:choice>
        </xs:sequence>
        <xs:attribute name="RootFolder" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="SoundFile">
    <xs:complexContent mixed="false">
      <xs:extension base="XResource" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="XResource" abstract="true">
    <xs:complexContent mixed="false">
      <xs:extension base="XObject">
        <xs:attribute name="Source" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="MusicFile">
    <xs:complexContent mixed="false">
      <xs:extension base="XResource" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Texture">
    <xs:complexContent mixed="false">
      <xs:extension base="XResource" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Font">
    <xs:complexContent mixed="false">
      <xs:extension base="XResource" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Dashboard">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="TapArea">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement">
        <xs:attribute name="Event" type="xs:string" />
        <xs:attribute name="Action" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Include">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement">
        <xs:attribute name="File" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Music">
    <xs:complexContent mixed="false">
      <xs:extension base="XObject">
        <xs:sequence>
          <xs:element minOccurs="1" maxOccurs="1" name="InProgress" type="xs:boolean" />
        </xs:sequence>
        <xs:attribute name="FileId" type="xs:string" />
        <xs:attribute name="Volume" type="xs:float" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Sound">
    <xs:complexContent mixed="false">
      <xs:extension base="XObject">
        <xs:sequence>
          <xs:element minOccurs="1" maxOccurs="1" name="InProgress" type="xs:boolean" />
        </xs:sequence>
        <xs:attribute name="FileId" type="xs:string" />
        <xs:attribute name="Pitch" type="xs:float" use="required" />
        <xs:attribute name="Pan" type="xs:float" use="required" />
        <xs:attribute name="IsLooped" type="xs:boolean" use="required" />
        <xs:attribute name="Volume" type="xs:float" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Viewport">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="LevelSettings">
    <xs:complexContent mixed="false">
      <xs:extension base="XObject">
        <xs:attribute name="Difficulty" type="xs:int" use="required" />
        <xs:attribute name="BombCount" type="xs:int" use="required" />
        <xs:attribute name="HeroHealth" type="xs:float" use="required" />
        <xs:attribute name="ExplosionClass" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Layer">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="IntersectionTrigger">
    <xs:complexContent mixed="false">
      <xs:extension base="XNumTriggerBase">
        <xs:attribute name="ObjectId1" type="xs:string" />
        <xs:attribute name="ObjectId2" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="XNumTriggerBase" abstract="true">
    <xs:complexContent mixed="false">
      <xs:extension base="XTriggerBase">
        <xs:attribute name="Value" type="xs:string" />
        <xs:attribute name="Compare" type="XValueComparison" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="XTriggerBase" abstract="true">
    <xs:complexContent mixed="false">
      <xs:extension base="XObject">
        <xs:attribute name="EnterAction" type="xs:string" />
        <xs:attribute name="ExitAction" type="xs:string" />
        <xs:attribute name="Action" type="xs:string" />
        <xs:attribute name="Group" type="xs:string" />
        <xs:attribute name="StayTriggered" type="xs:boolean" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="BoolTrigger">
    <xs:complexContent mixed="false">
      <xs:extension base="XTriggerBase">
        <xs:attribute name="Condition" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:simpleType name="XValueComparison">
    <xs:restriction base="xs:string">
      <xs:enumeration value="E" />
      <xs:enumeration value="G" />
      <xs:enumeration value="GE" />
      <xs:enumeration value="L" />
      <xs:enumeration value="LE" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="NumTrigger">
    <xs:complexContent mixed="false">
      <xs:extension base="XNumTriggerBase">
        <xs:attribute name="Property" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DistanceTrigger">
    <xs:complexContent mixed="false">
      <xs:extension base="XNumTriggerBase">
        <xs:attribute name="ObjectId1" type="xs:string" />
        <xs:attribute name="ObjectId2" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Class">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Tower">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement">
        <xs:attribute name="SignalSpeed" type="xs:double" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Hero">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement">
        <xs:attribute name="Speed" type="xs:float" use="required" />
        <xs:attribute name="Direction" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Enemy">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement">
        <xs:attribute name="Damage" type="xs:float" use="required" />
        <xs:attribute name="IsExploding" type="xs:boolean" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Food">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement">
        <xs:attribute name="Points" type="xs:float" use="required" />
        <xs:attribute name="IsExploding" type="xs:boolean" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Explosion">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement">
        <xs:attribute name="Ranges" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Text">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement">
        <xs:attribute name="Text" type="xs:string" />
        <xs:attribute name="FontId" type="xs:string" />
        <xs:attribute name="Color" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Block">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement">
        <xs:attribute name="Edges" type="XEdgeType" use="required" />
        <xs:attribute name="IsExploding" type="xs:boolean" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:simpleType name="XEdgeType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="None" />
      <xs:enumeration value="Bounce" />
      <xs:enumeration value="Stick" />
      <xs:enumeration value="Teleport" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="KeyFrame">
    <xs:complexContent mixed="false">
      <xs:extension base="XObject">
        <xs:attribute name="Value" type="xs:string" />
        <xs:attribute name="Smoothing" type="CurveTangent" use="required" />
        <xs:attribute name="Time" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Group">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement">
        <xs:attribute name="IsExploding" type="xs:boolean" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Image">
    <xs:complexContent mixed="false">
      <xs:extension base="XElement">
        <xs:attribute name="TextureId" type="xs:string" />
        <xs:attribute name="Stretch" type="xs:boolean" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Sprite">
    <xs:complexContent mixed="false">
      <xs:extension base="Image">
        <xs:attribute name="FrameCount" type="xs:int" use="required" />
        <xs:attribute name="CurrentFrame" type="xs:int" use="required" />
        <xs:attribute name="FrameBounds" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Delay">
    <xs:complexContent mixed="false">
      <xs:extension base="XObject">
        <xs:sequence>
          <xs:element minOccurs="1" maxOccurs="1" name="InProgress" type="xs:boolean" />
        </xs:sequence>
        <xs:attribute name="Duration" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
</xs:schema>

=== valsavva/DynaCat/Source/Lunohod/Lunohod/Metadata/Lvl_1D_Zamanuha_v2.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- SVG to XGAME xml converter v1.6.04 -->
<!-- source: D:\Lunohod\Levels\Lvl_1D_Zamanuha_v2\Lvl_1D_Zamanuha_v2.svg -->
<Level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/Lunohod/Documentation/schema0.xsd" Name="Lvl_1D_Zamanuha_v2" Bounds="0, 0, 480, 320">
    <Include File="ClassFood.xml" />
    <Include File="ClassTower.xml" />
    <Include File="ClassExit.xml" />
    <Include File="ClassHero.xml" />
    <Resources RootFolder="Textures">
        <Texture Id="txr_brickWall" Source="brickWall" />
        <Texture Id="txr_laz_hor" Source="laz_hor" />
        <Texture Id="txr_laz_bckgrnd" Source="laz_bckgrnd" />
        <Texture Id="txr_fish_5_me" Source="fish_5_me" />
        <Texture Id="txr_container_steel_2" Source="container_steel_2" />
    </Resources>
    <Layer Id="background" BackColor="#FFFFFFFF">
        <Image Id="dfltMask1" TextureId="txr_brickWall" Bounds="0, 0, 480, 320" TraceId="image4550"/>
    </Layer>
    <Layer Id="laz" BackColor="#FFFFFFFF">
        <Image Id="dfltMask2" TextureId="txr_laz_hor" Bounds="160, 60, 40, 30" TraceId="image3109"/>
        <Image Id="dfltMask3" TextureId="txr_laz_bckgrnd" Bounds="220, 70, 40, 30" TraceId="image3035"/>
        <Image Id="dfltMask4" TextureId="txr_laz_bckgrnd" Bounds="260, 70, 40, 30" TraceId="image3056"/>
        <Image Id="dfltMask5" TextureId="txr_laz_bckgrnd" Bounds="260, 100, 40, 30" TraceId="image3058"/>
        <Image Id="dfltMask6" TextureId="txr_laz_bckgrnd" Bounds="220, 100, 40, 30" TraceId="image3060"/>
        <Image Id="dfltMask7" TextureId="txr_laz_bckgrnd" Bounds="300, 70, 40, 30" TraceId="image3063"/>
        <Image Id="dfltMask8" TextureId="txr_laz_bckgrnd" Bounds="300, 100, 40, 30" TraceId="image3066"/>
        <Image Id="dfltMask9" TextureId="txr_laz_bckgrnd" Bounds="180, 70, 40, 30" TraceId="image3068"/>
        <Image Id="dfltMask10" TextureId="txr_laz_bckgrnd" Bounds="180, 100, 40, 30" TraceId="image3070"/>
        <Image Id="dfltMask11" TextureId="txr_laz_bckgrnd" Bounds="220, 40, 40, 30" TraceId="image3072"/>
        <Image Id="dfltMask12" TextureId="txr_laz_bckgrnd" Bounds="260, 40, 40, 30" TraceId="image3074"/>
        <Image Id="dfltMask13" TextureId="txr_laz_bckgrnd" Bounds="300, 40, 40, 30" TraceId="image3076"/>
        <Image Id="dfltMask14" TextureId="txr_laz_bckgrnd" Bounds="180, 40, 40, 30" TraceId="image3078"/>
        <Image Id="dfltMask15" TextureId="txr_laz_bckgrnd" Bounds="260, 130, 40, 30" TraceId="image3080"/>
        <Image Id="dfltMask16" TextureId="txr_laz_bckgrnd" Bounds="220, 130, 40, 30" TraceId="image3082"/>
        <Image Id="dfltMask17" TextureId="txr_laz_bckgrnd" Bounds="300, 130, 40, 30" TraceId="image3084"/>
        <Image Id="dfltMask18" TextureId="txr_laz_bckgrnd" Bounds="180, 130, 40, 30" TraceId="image3086"/>
        <Image Id="dfltMask19" TextureId="txr_laz_hor" Bounds="120, 60, 40, 30" TraceId="image3096"/>
        <Image Id="dfltMask20" TextureId="txr_laz_hor" Bounds="80, 60, 40, 30" TraceId="image3099"/>
        <Image Id="dfltMask21" TextureId="txr_laz_hor" Bounds="40, 60, 40, 30" TraceId="image3101"/>
        <Image Id="dfltMask22" TextureId="txr_laz_hor" Bounds="0, 60, 40, 30" TraceId="image3103"/>
    </Layer>
    <Layer Id="action" BackColor="#FFFFFFFF">
        <Food Id="fd1" Class="clsFood" Points="100" Bounds="295, 136, 26, 17" TraceId="image3111">
            <Image TextureId="txr_fish_5_me" />
        </Food>
        <Food Id="fd2" Class="clsFood" Points="100" Bounds="307, 118, 26, 17" TraceId="image3065">
            <Image TextureId="txr_fish_5_me" />
        </Food>
        <Block Id="blk1" Bounds="266, 70, 30, 30" Edges="Bounce" TraceId="image3071">
            <Image TextureId="txr_container_steel_2" />
        </Block>
        <Block Id="blk2" Bounds="248, 102, 30, 30" Edges="Bounce" TraceId="image3073">
            <Image TextureId="txr_container_steel_2" />
        </Block>
    </Layer>
    <Layer Id="actionTHE" BackColor="#FFFFFFFF">
        <Tower Id="tower" Bounds="0, 0, 30, 30" Class="clsTower" TraceId="image3038"/>
        <Group Id="exit" Class="clsExit" Bounds="183, 104, 37, 54" TraceId="image3049" />
        <Hero Id="hero" Class="clsHero" Bounds="19, 63, 33, 24" TraceId="image3606"/>
    </Layer>
    <Layer Id="blocks" BackColor="#FFFFFFFF">
        <Block Id="blk3" Bounds="-50, 0, 50, 160" Edges="Stick" TraceId="image4576"/>
        <Block Id="blk4" Bounds="-20, 10, 200, 50" Edges="Stick" TraceId="image4579"/>
        <Block Id="blk5" Bounds="340, 0, 50, 160" Edges="Stick" TraceId="image4587"/>
        <Block Id="blk6" Bounds="-20, 90, 200, 166" Edges="Stick" TraceId="image3034"/>
        <Block Id="blk7" Bounds="180, 160, 200, 166" Edges="Stick" TraceId="image3036"/>
        <Block Id="blk8" Bounds="180, -126, 200, 166" Edges="Stick" TraceId="image3039"/>
    </Layer>
    <Include File="ClassExplosion.xml" />
    <Include File="Dashboard.xml" />
</Level>
<!-- Food=2 Enemy=0 Block=8 DesignImage=22 Animation=0 Teleport Animations=0 FoodPack=0 -->
<!-- -->
<!-- Food Points = 200 -->
<!-- 1% = 2; 45% = 90; 90% = 180 -->
<!-- minPointsFood = 100 (50%) -->

=== valsavva/DynaCat/Source/Lunohod/Lunohod/Metadata/ClassUIButton.xml
<!--<Level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/Lunohod/Documentation/schema0.xsd" Name="Lvl_1D_Boxes" Bounds="0, 0, 480, 320">-->
    
<Include>
    <Resources RootFolder="Global">
        <Texture Id="txrUiBtn_back_N" Source="ui_btn_back_01" />
        <Texture Id="txrUiBtn_back_P" Source="ui_btn_back_03" />
        <Texture Id="txrUiBtn_next_N" Source="ui_btn_next_01" />
        <Texture Id="txrUiBtn_next_P" Source="ui_btn_next_03" />
        <Texture Id="txrUiBtn_forwind_N" Source="ui_btn_forwind_01" />
        <Texture Id="txrUiBtn_forwind_P" Source="ui_btn_forwind_03" />
        <Texture Id="txrUiBtn_full version_N" Source="ui_btn_full version_01" />
        <Texture Id="txrUiBtn_full version_P" Source="ui_btn_full version_03" />
        <Texture Id="txrUiBtn_info_N" Source="ui_btn_info_01" />
        <Texture Id="txrUiBtn_info_P" Source="ui_btn_info_03" />
        <Texture Id="txrUiBtn_exit_N" Source="ui_btn_exit_01" />
        <Texture Id="txrUiBtn_exit_P" Source="ui_btn_exit_03" />
        <Texture Id="txrUiBtn_play_N" Source="ui_btn_play_01" />
        <Texture Id="txrUiBtn_play_P" Source="ui_btn_play_03" />
        <Texture Id="txrUiBtn_restart_N" Source="ui_btn_restart_01" />
        <Texture Id="txrUiBtn_restart_P" Source="ui_btn_restart_03" />
    </Resources>
    <Resources RootFolder="Sound">
        <SoundFile Id="sndButtonTapped" Source="btn_click"/>
    </Resources>

    
    
    <Class Id="clsButton">
		<Group>
            <Sound Id="this_sndButtonTapped" FileId="sndButtonTapped" Volume="0.5" Pitch="0"/>

            <!-- button is pressed -->
            <SequenceSet Id="this_setPressed" RepeatCount="1" InProgress="false">
                <Do Action="this_sndButtonTapped.Start()" />
                <Delay Duration="0.1" /> <!-- pause for animation and fxs -->
                <Do Action="this:Action;" />
            </SequenceSet>

            <TapArea Id="this_tapArea" Action="this_setPressed.Play();"/>

            <!-- state : basic, not pressed -->
            <BoolTrigger Condition="not this_setPressed.InProgress" 
                         Group="this_sttButton">
                <Image TextureId="txrUiBtn_@BtnImg_N" StretchMode="ActualSize" />
            </BoolTrigger>
            
            <!-- state : pressed -->
            <BoolTrigger Group="this_sttButton">
                <Image TextureId="txrUiBtn_@BtnImg_P" StretchMode="ActualSize" />
            </BoolTrigger>
		</Group>
	</Class>
	
</Include>
